apiVersion: v1
kind: Service
metadata:
  name: alerts-service
spec:
  selector:
    app: alerts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts
spec:
  selector:
    matchLabels:
      app: alerts
  replicas: 2
  template:
    metadata:
      labels:
        app: alerts
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: billing-key
      containers:
        - name: alerts
          image: gcr.io/<GCP_PROJECT>/alerts:<IMAGE_VERSION>
          imagePullPolicy: "Always"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-api-key
                  key: apikey
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid-api-key
                  key: apikey
            - name: BILLING_ALERT_TEMPLATE_ID
              valueFrom:
                configMapKeyRef:
                  key: BILLING_ALERT_TEMPLATE_ID
                  name: environment-config
            - name: CUSTOMER_DETAILS_API
              value: "http://customerdetails-service.default.svc.cluster.local"
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  key: projectID
                  name: environment-config
            - name: BILLING_BQ_DATASET
              valueFrom:
                configMapKeyRef:
                  key: billingBQDataset
                  name: environment-config
            - name: BILLING_BQ_TABLE_BY_PROJECT
              valueFrom:
                configMapKeyRef:
                  key: billingBQTableByProject
                  name: environment-config
            - name: BILLING_BQ_TABLE_BY_PROJECT_MONTHLY
              valueFrom:
                configMapKeyRef:
                  key: billingBQTableByProjectMonthly
                  name: environment-config
            - name: BILLING_BQ_TABLE_BY_PRODUCT
              valueFrom:
                configMapKeyRef:
                  key: billingBQTableByProduct
                  name: environment-config
            - name: BILLING_BQ_TABLE_BY_PRODUCT_MONTHLY
              valueFrom:
                configMapKeyRef:
                  key: billingBQTableByProductMonthly
                  name: environment-config
            - name: BILLING_ALERTS_TOPIC_ID
              valueFrom:
                configMapKeyRef:
                  key: BILLING_ALERTS_TOPIC_ID
                  name: environment-config
            - name: BILLING_ALERTS_SUBSCRIPTION_ID
              valueFrom:
                configMapKeyRef:
                  key: BILLING_ALERTS_SUBSCRIPTION_ID
                  name: environment-config
            - name: CC_WEBSITE
              valueFrom:
                configMapKeyRef:
                  key: CC_WEBSITE
                  name: environment-config
            - name: ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: origins
                  name: environment-config
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              port: 8001
              path: /alerts/docs
          readinessProbe:
            httpGet:
              port: 8001
              path: /alerts/docs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alerts-producer
  namespace: default
spec:
  schedule: 00 6 * * *  # at 7:00 AM Portugal everyday
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: billing-key
          containers:
            - image: gcr.io/<GCP_PROJECT>/alerts:<IMAGE_VERSION>
              args:
                - python
                - -m
                - app.producer
              name: alerts-producer
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
              env:
                - name: DEBUG
                  value: "True"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
                - name: FIREBASE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: firebase-api-key
                      key: apikey
                - name: SENDGRID_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: sendgrid-api-key
                      key: apikey
                - name: BILLING_ALERT_TEMPLATE_ID
                  valueFrom:
                    configMapKeyRef:
                      key: BILLING_ALERT_TEMPLATE_ID
                      name: environment-config
                - name: CUSTOMER_DETAILS_API
                  value: "http://customerdetails-service.default.svc.cluster.local"
                - name: GCP_PROJECT_ID
                  valueFrom:
                    configMapKeyRef:
                      key: projectID
                      name: environment-config
                - name: BILLING_BQ_DATASET
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQDataset
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PROJECT
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProject
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PROJECT_MONTHLY
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProjectMonthly
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PRODUCT
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProduct
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PRODUCT_MONTHLY
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProductMonthly
                      name: environment-config
                - name: BILLING_ALERTS_TOPIC_ID
                  valueFrom:
                    configMapKeyRef:
                      key: BILLING_ALERTS_TOPIC_ID
                      name: environment-config
                - name: BILLING_ALERTS_SUBSCRIPTION_ID
                  valueFrom:
                    configMapKeyRef:
                      key: BILLING_ALERTS_SUBSCRIPTION_ID
                      name: environment-config
                - name: CC_WEBSITE
                  valueFrom:
                    configMapKeyRef:
                      key: CC_WEBSITE
                      name: environment-config
                - name: ORIGINS
                  valueFrom:
                    configMapKeyRef:
                      key: origins
                      name: environment-config
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alerts-consumer
  namespace: default
spec:
  schedule: 30 6 * * *  # at 7:30 AM Portugal everyday
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: billing-key
          containers:
            - image: gcr.io/<GCP_PROJECT>/alerts:<IMAGE_VERSION>
              args:
                - python
                - -m
                - app.consumer
              name: alerts-consumer
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
              env:
                - name: DEBUG
                  value: "True"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
                - name: FIREBASE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: firebase-api-key
                      key: apikey
                - name: SENDGRID_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: sendgrid-api-key
                      key: apikey
                - name: BILLING_ALERT_TEMPLATE_ID
                  valueFrom:
                    configMapKeyRef:
                      key: BILLING_ALERT_TEMPLATE_ID
                      name: environment-config
                - name: CUSTOMER_DETAILS_API
                  value: "http://customerdetails-service.default.svc.cluster.local"
                - name: GCP_PROJECT_ID
                  valueFrom:
                    configMapKeyRef:
                      key: projectID
                      name: environment-config
                - name: BILLING_BQ_DATASET
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQDataset
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PROJECT
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProject
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PROJECT_MONTHLY
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProjectMonthly
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PRODUCT
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProduct
                      name: environment-config
                - name: BILLING_BQ_TABLE_BY_PRODUCT_MONTHLY
                  valueFrom:
                    configMapKeyRef:
                      key: billingBQTableByProductMonthly
                      name: environment-config
                - name: BILLING_ALERTS_TOPIC_ID
                  valueFrom:
                    configMapKeyRef:
                      key: BILLING_ALERTS_TOPIC_ID
                      name: environment-config
                - name: BILLING_ALERTS_SUBSCRIPTION_ID
                  valueFrom:
                    configMapKeyRef:
                      key: BILLING_ALERTS_SUBSCRIPTION_ID
                      name: environment-config
                - name: CC_WEBSITE
                  valueFrom:
                    configMapKeyRef:
                      key: CC_WEBSITE
                      name: environment-config
                - name: ORIGINS
                  valueFrom:
                    configMapKeyRef:
                      key: origins
                      name: environment-config
          restartPolicy: OnFailure
