name: Build and Unittest

on: workflow_dispatch
#on:
#  push:
#      branches:
#        - main

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_REGION: ${{ secrets.GKE_REGION }}

jobs:
  setup-build-unittest:
    name: Setup, Build and Unittest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          #export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      # Get the content of the Service Account from Secret Manager
      - name: Get secrets from Secret Manager
        run: |
          gcloud secrets versions access latest \
          --secret=ci_unittest_sa > /workspace/ci_unittest_sa.json
      
      # Get the content the env file from Secret Manager
      - name: Get content of env file from Secret Manager
        run: |
          gcloud secrets versions access latest \
          --secret=ci_unittest_env > /workspace/.env

      # Run Unittest
      - name: Unittest
        run: |-
          docker run \
          --rm \
          --env-file /workspace/.env \
          -v /workspace:/app:ro \
          -e GOOGLE_APPLICATION_CREDENTIALS=/app/ci_unittest_sa.json \
          gcr.io/$PROJECT_ID/$SERVICE_NAME:$SHORT_SHA \
          python \
          -m pytest
      


