name: Build and Deploy to GKE

on: workflow_dispatch
#on:
#  push:
#      branches:
#        - main

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_REGION: ${{ secrets.GKE_REGION }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          #export_default_credentials: true
      
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
          -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --build-arg SHA_CLOUDBUILD=$SHORT_SHA \
          . \
          --cache-from gcr.io/$PROJECT_ID/$SERVICE_NAME
      
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy to Kubernetes
      - name: Deploy
        run: |-
          kubectl apply -f deployment.yaml --record=true
